"use client";

import { GitCompareArrows, ShieldCheck } from "lucide-react";
import Link from "next/link";
import { useMemo, useState } from "react";

import { fromPublic } from "@/components/answer/answer-model";
import { AnswerView } from "@/components/answer/answer-view";
import { StatusPill } from "@/components/clinical/badges";
import { LocalTime } from "@/components/clinical/local-time";
import { Button } from "@/components/ui/button";
import { asCitations, type Confidence, type Schemas } from "@/lib/domain";

export function PublicAnswer({ page }: { page: Schemas["PublicAnswerOut"] }) {
  const answer = useMemo(() => fromPublic(page), [page]);
  const [showLatest, setShowLatest] = useState(false);
  const superseded = page.superseded;

  const latest = useMemo(() => {
    if (!superseded) return null;
    return {
      ...answer,
      content: superseded.content,
      citations: asCitations(superseded.citations),
      confidence: (superseded.confidence as Confidence | null) ?? answer.confidence,
      answeredAt: superseded.superseded_at,
    };
  }, [answer, superseded]);

  return (
    <div className="min-h-screen bg-background">
      <header className="border-b bg-card">
        <div className="mx-auto flex max-w-6xl items-center gap-3 px-4 py-3 md:px-6">
          <span className="grid size-6 place-items-center rounded-sm bg-primary font-mono text-xs font-bold text-primary-foreground">CC</span>
          <span className="font-semibold tracking-tight">ClinicalContext</span>
          <span className="text-sm text-muted-foreground">· shared by {page.organization}</span>
          <Button size="sm" variant="outline" className="ml-auto" nativeButton={false} render={<Link href="/login" />}>
            Sign in
          </Button>
        </div>
      </header>

      <main className="mx-auto flex max-w-6xl flex-col gap-4 p-4 md:p-6">
        {superseded && (
          <div role="alert" className="flex flex-wrap items-center gap-3 rounded-lg border-2 border-conflict bg-conflict-bg p-4 text-conflict-fg">
            <GitCompareArrows className="size-5 shrink-0" aria-hidden />
            <div className="min-w-0 flex-1">
              <p className="font-semibold">This answer has been superseded.</p>
              <p className="text-sm">
                A re-query on <LocalTime iso={superseded.superseded_at} /> (v{superseded.latest_version}) found the evidence had changed
                {superseded.diff && Array.isArray(superseded.diff.reasons) && superseded.diff.reasons.length > 0
                  ? `: ${(superseded.diff.reasons as string[]).join("; ")}.`
                  : "."}
              </p>
            </div>
            <Button size="sm" variant="outline" onClick={() => setShowLatest((v) => !v)} aria-pressed={showLatest}>
              {showLatest ? "Show original" : "Show the updated answer"}
            </Button>
          </div>
        )}

        <div className="flex flex-wrap items-center gap-2 text-sm text-muted-foreground">
          <h1 className="w-full text-lg font-semibold tracking-tight text-foreground">{page.query}</h1>
          {superseded && <StatusPill kind="superseded" />}
          <span>
            Answered <LocalTime iso={page.answered_at} options={{ dateStyle: "medium", timeStyle: "short" }} />
          </span>
          <span aria-hidden>·</span>
          <span className="inline-flex items-center gap-1">
            <ShieldCheck className="size-3.5" aria-hidden /> Every claim links to its source passage
          </span>
        </div>

        <AnswerView answer={showLatest && latest ? latest : answer} readOnly showFeedback={false} />

        <footer className="border-t pt-4 text-xs text-muted-foreground">
          Generated by ClinicalContext from published clinical literature ({page.model}, prompts {page.prompt_version}). It
          summarises evidence and does not replace clinical judgement or emergency care.
        </footer>
      </main>
    </div>
  );
}
