"""The Learn tab's map of medicine: every MBBS subject and the PG specialties.

Subjects follow India's competency-based MBBS curriculum (pre-clinical,
para-clinical and clinical phases) and the broad (MD/MS) and super-specialty
(DM/MCh) postgraduate branches. Each carries the PubMed search that defines
its literature — used for the "latest research" feed and for the nightly job
that keeps the shared corpus current — and a starter list of core topics a
student or doctor can open for a sourced explainer.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

Level = Literal["preclinical", "paraclinical", "clinical", "pg_broad", "pg_super"]

LEVEL_LABELS: dict[Level, str] = {
    "preclinical": "MBBS · Pre-clinical",
    "paraclinical": "MBBS · Para-clinical",
    "clinical": "MBBS · Clinical",
    "pg_broad": "PG · MD / MS",
    "pg_super": "PG · DM / MCh",
}


@dataclass(frozen=True, slots=True)
class Specialty:
    slug: str
    name: str
    level: Level
    pubmed: str
    topics: tuple[str, ...]


SPECIALTIES: tuple[Specialty, ...] = (
    # -- MBBS pre-clinical --------------------------------------------------------------
    Specialty(
        "anatomy",
        "Anatomy",
        "preclinical",
        '"anatomy"[MeSH Terms] OR "anatomy/education"[MeSH Terms]',
        (
            "Brachial plexus and its injuries",
            "Coronary circulation",
            "Inguinal canal and hernias",
            "Portal venous system",
            "Cranial nerves",
            "Circle of Willis",
            "Rotator cuff",
            "Development of the heart",
        ),
    ),
    Specialty(
        "physiology",
        "Physiology",
        "preclinical",
        '"physiology"[MeSH Terms] OR "physiology/education"[MeSH Terms]',
        (
            "Cardiac cycle",
            "Renal handling of sodium and water",
            "Oxygen-haemoglobin dissociation curve",
            "Action potential and synaptic transmission",
            "Regulation of blood pressure",
            "Acid-base balance",
            "Hypothalamic-pituitary axis",
            "Physiology of pain",
        ),
    ),
    Specialty(
        "biochemistry",
        "Biochemistry",
        "preclinical",
        '"biochemistry"[MeSH Terms] OR "metabolic diseases"[MeSH Terms]',
        (
            "Glycolysis and its regulation",
            "Lipoprotein metabolism",
            "Urea cycle disorders",
            "Vitamin B12 and folate",
            "Enzyme kinetics",
            "Inborn errors of metabolism",
            "Iron metabolism",
            "Liver function tests",
        ),
    ),
    # -- MBBS para-clinical ------------------------------------------------------------
    Specialty(
        "pathology",
        "Pathology",
        "paraclinical",
        '"pathology"[MeSH Terms] OR "pathology, clinical"[MeSH Terms]',
        (
            "Inflammation and repair",
            "Neoplasia: hallmarks of cancer",
            "Anaemia classification",
            "Haemodynamic disorders and thrombosis",
            "Amyloidosis",
            "Leukaemias and lymphomas",
            "Glomerular diseases",
            "Atherosclerosis",
        ),
    ),
    Specialty(
        "microbiology",
        "Microbiology",
        "paraclinical",
        '"microbiology"[MeSH Terms] OR "communicable diseases"[MeSH Terms]',
        (
            "Antimicrobial resistance",
            "Mycobacterium tuberculosis",
            "Hospital-acquired infections",
            "Dengue virus",
            "Malaria parasites",
            "Salmonella Typhi",
            "HIV",
            "Sterilisation and disinfection",
        ),
    ),
    Specialty(
        "pharmacology",
        "Pharmacology",
        "paraclinical",
        '"pharmacology, clinical"[MeSH Terms] OR "drug therapy"[MeSH Terms]',
        (
            "Pharmacokinetics",
            "Antihypertensive drugs",
            "Antimicrobial stewardship",
            "Anticoagulants",
            "Insulin and oral antidiabetic drugs",
            "Adverse drug reactions",
            "Drug interactions",
            "Opioid analgesics",
        ),
    ),
    Specialty(
        "forensic-medicine",
        "Forensic Medicine & Toxicology",
        "paraclinical",
        '"forensic medicine"[MeSH Terms] OR "poisoning"[MeSH Terms]',
        (
            "Organophosphate poisoning",
            "Snake bite envenomation",
            "Paracetamol overdose",
            "Postmortem changes",
            "Medical negligence",
            "Wound examination",
            "Methanol poisoning",
            "Paraquat and aluminium phosphide poisoning",
        ),
    ),
    # -- MBBS clinical -----------------------------------------------------------------
    Specialty(
        "community-medicine",
        "Community Medicine (PSM)",
        "clinical",
        '"public health"[MeSH Terms] OR "preventive medicine"[MeSH Terms] '
        'OR "vaccination"[MeSH Terms]',
        (
            "Immunisation schedule",
            "Epidemiology of tuberculosis in India",
            "Screening tests: sensitivity and specificity",
            "Study designs",
            "Vector-borne diseases",
            "Nutrition programmes",
            "Biomedical waste management",
            "Non-communicable disease prevention",
        ),
    ),
    Specialty(
        "general-medicine",
        "General Medicine",
        "clinical",
        '"internal medicine"[MeSH Terms]',
        (
            "Hypertension",
            "Type 2 diabetes",
            "Heart failure",
            "Community-acquired pneumonia",
            "Chronic kidney disease",
            "Dengue",
            "Enteric fever",
            "Acute coronary syndrome",
        ),
    ),
    Specialty(
        "general-surgery",
        "General Surgery",
        "clinical",
        '"general surgery"[MeSH Terms] OR "surgical procedures, operative"[MeSH Terms]',
        (
            "Acute appendicitis",
            "Gallstone disease",
            "Hernia repair",
            "Breast lump evaluation",
            "Trauma: primary survey (ATLS)",
            "Intestinal obstruction",
            "Surgical site infection",
            "Thyroid nodules",
        ),
    ),
    Specialty(
        "obstetrics-gynaecology",
        "Obstetrics & Gynaecology",
        "clinical",
        '"obstetrics"[MeSH Terms] OR "gynecology"[MeSH Terms] OR "pregnancy complications"',
        (
            "Pre-eclampsia",
            "Postpartum haemorrhage",
            "Gestational diabetes",
            "Antenatal care",
            "Polycystic ovary syndrome",
            "Anaemia in pregnancy",
            "Cervical cancer screening",
            "Ectopic pregnancy",
        ),
    ),
    Specialty(
        "paediatrics",
        "Paediatrics",
        "clinical",
        '"pediatrics"[MeSH Terms] OR child[MeSH Terms] AND therapy',
        (
            "Fever in children",
            "Acute diarrhoea and dehydration",
            "Severe acute malnutrition",
            "Neonatal jaundice",
            "Childhood pneumonia",
            "Growth and development milestones",
            "Bronchiolitis",
            "Febrile seizures",
        ),
    ),
    Specialty(
        "orthopaedics",
        "Orthopaedics",
        "clinical",
        '"orthopedics"[MeSH Terms] OR fractures, bone[MeSH Terms]',
        (
            "Fracture neck of femur",
            "Osteoarthritis knee",
            "Low back pain",
            "Osteomyelitis",
            "Supracondylar fracture humerus",
            "Osteoporosis",
            "Carpal tunnel syndrome",
            "Clubfoot",
        ),
    ),
    Specialty(
        "ophthalmology",
        "Ophthalmology",
        "clinical",
        '"ophthalmology"[MeSH Terms] OR "eye diseases"[MeSH Terms]',
        (
            "Cataract",
            "Glaucoma",
            "Diabetic retinopathy",
            "Conjunctivitis",
            "Refractive errors",
            "Red eye evaluation",
            "Retinal detachment",
            "Vitamin A deficiency",
        ),
    ),
    Specialty(
        "ent",
        "Otorhinolaryngology (ENT)",
        "clinical",
        '"otolaryngology"[MeSH Terms] OR "otorhinolaryngologic diseases"[MeSH Terms]',
        (
            "Acute otitis media",
            "Chronic suppurative otitis media",
            "Allergic rhinitis",
            "Epistaxis",
            "Tonsillitis",
            "Sensorineural hearing loss",
            "Sinusitis",
            "Vertigo",
        ),
    ),
    Specialty(
        "dermatology",
        "Dermatology",
        "clinical",
        '"dermatology"[MeSH Terms] OR "skin diseases"[MeSH Terms]',
        (
            "Psoriasis",
            "Atopic dermatitis",
            "Acne vulgaris",
            "Dermatophyte (tinea) infections",
            "Scabies",
            "Leprosy",
            "Vitiligo",
            "Urticaria",
        ),
    ),
    Specialty(
        "psychiatry",
        "Psychiatry",
        "clinical",
        '"psychiatry"[MeSH Terms] OR "mental disorders"[MeSH Terms]',
        (
            "Major depressive disorder",
            "Schizophrenia",
            "Bipolar disorder",
            "Generalised anxiety disorder",
            "Alcohol use disorder",
            "Suicide risk assessment",
            "ADHD",
            "Dementia",
        ),
    ),
    Specialty(
        "anaesthesiology",
        "Anaesthesiology",
        "clinical",
        '"anesthesiology"[MeSH Terms] OR anesthesia[MeSH Terms]',
        (
            "Pre-anaesthetic evaluation",
            "Airway management",
            "Local anaesthetic toxicity",
            "Malignant hyperthermia",
            "Spinal and epidural anaesthesia",
            "Postoperative nausea and vomiting",
            "Sepsis and fluid resuscitation",
            "Neuromuscular blockade",
        ),
    ),
    Specialty(
        "radiology",
        "Radiodiagnosis",
        "clinical",
        '"radiology"[MeSH Terms] OR "diagnostic imaging"[MeSH Terms]',
        (
            "Chest X-ray interpretation",
            "CT in head injury",
            "Ultrasound in acute abdomen",
            "MRI safety",
            "Radiation protection",
            "Contrast-induced nephropathy",
            "Imaging in stroke",
            "Point-of-care ultrasound",
        ),
    ),
    Specialty(
        "emergency-medicine",
        "Emergency Medicine",
        "clinical",
        '"emergency medicine"[MeSH Terms] OR "emergencies"[MeSH Terms]',
        (
            "Cardiac arrest (ACLS)",
            "Anaphylaxis",
            "Sepsis",
            "Acute stroke",
            "Diabetic ketoacidosis",
            "Status epilepticus",
            "Acute asthma",
            "Poisoning: initial management",
        ),
    ),
    Specialty(
        "respiratory-medicine",
        "Respiratory Medicine",
        "pg_broad",
        '"pulmonary medicine"[MeSH Terms] OR "lung diseases"[MeSH Terms]',
        (
            "Asthma",
            "COPD",
            "Tuberculosis treatment",
            "Interstitial lung disease",
            "Pleural effusion",
            "Obstructive sleep apnoea",
            "Pulmonary embolism",
            "Bronchiectasis",
        ),
    ),
    Specialty(
        "family-medicine",
        "Family Medicine",
        "pg_broad",
        '"family practice"[MeSH Terms] OR "primary health care"[MeSH Terms]',
        (
            "Hypertension in primary care",
            "Antibiotic prescribing for respiratory infections",
            "Diabetes follow-up",
            "Common skin conditions",
            "Depression screening",
            "Vaccination in adults",
            "Chronic pain",
            "Polypharmacy in older adults",
        ),
    ),
    Specialty(
        "geriatrics",
        "Geriatric Medicine",
        "pg_broad",
        '"geriatrics"[MeSH Terms] OR "aged"[MeSH Terms] AND "frailty"',
        (
            "Frailty",
            "Falls",
            "Delirium",
            "Polypharmacy and deprescribing",
            "Dementia care",
            "Sarcopenia",
            "Urinary incontinence",
            "End-of-life care",
        ),
    ),
    Specialty(
        "radiation-oncology",
        "Radiation Oncology",
        "pg_broad",
        '"radiation oncology"[MeSH Terms] OR radiotherapy[MeSH Terms]',
        (
            "Radiotherapy in cervical cancer",
            "Head and neck cancer radiotherapy",
            "Radiation side effects",
            "Stereotactic radiosurgery",
            "Palliative radiotherapy",
            "Breast cancer radiotherapy",
            "Brachytherapy",
            "Radiation dermatitis",
        ),
    ),
    Specialty(
        "pmr",
        "Physical Medicine & Rehabilitation",
        "pg_broad",
        '"physical and rehabilitation medicine"[MeSH Terms] OR rehabilitation[MeSH Terms]',
        (
            "Stroke rehabilitation",
            "Spinal cord injury",
            "Cerebral palsy",
            "Amputee rehabilitation",
            "Low back pain rehabilitation",
            "Spasticity",
            "Cardiac rehabilitation",
            "Pressure injuries",
        ),
    ),
    # -- PG super-specialties -----------------------------------------------------------
    Specialty(
        "cardiology",
        "Cardiology",
        "pg_super",
        '"cardiology"[MeSH Terms] OR "cardiovascular diseases"[MeSH Terms]',
        (
            "Atrial fibrillation",
            "Acute coronary syndromes",
            "Heart failure with reduced ejection fraction",
            "Rheumatic heart disease",
            "Hypertension guidelines",
            "Dyslipidaemia",
            "Infective endocarditis",
            "Pulmonary hypertension",
        ),
    ),
    Specialty(
        "neurology",
        "Neurology",
        "pg_super",
        '"neurology"[MeSH Terms] OR "nervous system diseases"[MeSH Terms]',
        (
            "Acute ischaemic stroke",
            "Epilepsy",
            "Migraine",
            "Parkinson's disease",
            "Guillain-Barré syndrome",
            "Multiple sclerosis",
            "Myasthenia gravis",
            "Meningitis and encephalitis",
        ),
    ),
    Specialty(
        "nephrology",
        "Nephrology",
        "pg_super",
        '"nephrology"[MeSH Terms] OR "kidney diseases"[MeSH Terms]',
        (
            "Acute kidney injury",
            "Chronic kidney disease",
            "Nephrotic syndrome",
            "Dialysis",
            "Diabetic kidney disease",
            "Hyperkalaemia",
            "Kidney transplantation",
            "Glomerulonephritis",
        ),
    ),
    Specialty(
        "gastroenterology",
        "Gastroenterology & Hepatology",
        "pg_super",
        '"gastroenterology"[MeSH Terms] OR "digestive system diseases"[MeSH Terms]',
        (
            "Cirrhosis and its complications",
            "Upper GI bleeding",
            "Inflammatory bowel disease",
            "Acute pancreatitis",
            "Hepatitis B",
            "MASLD (fatty liver disease)",
            "Helicobacter pylori",
            "Irritable bowel syndrome",
        ),
    ),
    Specialty(
        "endocrinology",
        "Endocrinology",
        "pg_super",
        '"endocrinology"[MeSH Terms] OR "endocrine system diseases"[MeSH Terms]',
        (
            "Type 1 diabetes",
            "Hypothyroidism",
            "Hyperthyroidism",
            "Adrenal insufficiency",
            "Cushing's syndrome",
            "Osteoporosis",
            "Obesity pharmacotherapy",
            "Hyponatraemia",
        ),
    ),
    Specialty(
        "oncology",
        "Medical Oncology",
        "pg_super",
        '"medical oncology"[MeSH Terms] OR neoplasms[MeSH Terms] AND therapy',
        (
            "Breast cancer",
            "Lung cancer",
            "Colorectal cancer",
            "Immunotherapy adverse events",
            "Febrile neutropenia",
            "Tumour lysis syndrome",
            "Cancer pain",
            "Oral cancer",
        ),
    ),
    Specialty(
        "haematology",
        "Clinical Haematology",
        "pg_super",
        '"hematology"[MeSH Terms] OR "hematologic diseases"[MeSH Terms]',
        (
            "Iron deficiency anaemia",
            "Thalassaemia",
            "Sickle cell disease",
            "Immune thrombocytopenia",
            "Venous thromboembolism",
            "Acute leukaemia",
            "Multiple myeloma",
            "Transfusion reactions",
        ),
    ),
    Specialty(
        "rheumatology",
        "Rheumatology",
        "pg_super",
        '"rheumatology"[MeSH Terms] OR "rheumatic diseases"[MeSH Terms]',
        (
            "Rheumatoid arthritis",
            "Systemic lupus erythematosus",
            "Gout",
            "Ankylosing spondylitis",
            "Vasculitis",
            "Systemic sclerosis",
            "Polymyalgia rheumatica",
            "Septic arthritis",
        ),
    ),
    Specialty(
        "infectious-diseases",
        "Infectious Diseases",
        "pg_super",
        '"infectious disease medicine"[MeSH Terms] OR "infections"[MeSH Terms] AND treatment',
        (
            "Sepsis",
            "Tuberculosis",
            "HIV treatment",
            "Malaria",
            "Scrub typhus",
            "Leptospirosis",
            "Multidrug-resistant organisms",
            "Fungal infections in the immunocompromised",
        ),
    ),
    Specialty(
        "critical-care",
        "Critical Care Medicine",
        "pg_super",
        '"critical care"[MeSH Terms] OR "intensive care units"[MeSH Terms]',
        (
            "Septic shock",
            "ARDS",
            "Mechanical ventilation",
            "Vasopressors",
            "Fluid management",
            "Delirium in the ICU",
            "Nutrition in critical illness",
            "Brain death",
        ),
    ),
    Specialty(
        "neonatology",
        "Neonatology",
        "pg_super",
        '"neonatology"[MeSH Terms] OR "infant, newborn, diseases"[MeSH Terms]',
        (
            "Neonatal resuscitation",
            "Neonatal sepsis",
            "Respiratory distress syndrome",
            "Hypoxic-ischaemic encephalopathy",
            "Kangaroo mother care",
            "Neonatal hypoglycaemia",
            "Retinopathy of prematurity",
            "Breastfeeding",
        ),
    ),
    Specialty(
        "neurosurgery",
        "Neurosurgery",
        "pg_super",
        '"neurosurgery"[MeSH Terms] OR "neurosurgical procedures"[MeSH Terms]',
        (
            "Traumatic brain injury",
            "Subarachnoid haemorrhage",
            "Brain tumours",
            "Hydrocephalus",
            "Spinal cord compression",
            "Chronic subdural haematoma",
            "Lumbar disc herniation",
            "Raised intracranial pressure",
        ),
    ),
    Specialty(
        "cardiothoracic-surgery",
        "Cardiothoracic & Vascular Surgery",
        "pg_super",
        '"thoracic surgery"[MeSH Terms] OR "cardiac surgical procedures"[MeSH Terms]',
        (
            "Coronary artery bypass grafting",
            "Valve replacement",
            "Aortic dissection",
            "Peripheral arterial disease",
            "Varicose veins",
            "Lung resection",
            "Congenital heart surgery",
            "Empyema",
        ),
    ),
    Specialty(
        "urology",
        "Urology",
        "pg_super",
        '"urology"[MeSH Terms] OR "urologic diseases"[MeSH Terms]',
        (
            "Kidney stones",
            "Benign prostatic hyperplasia",
            "Prostate cancer",
            "Urinary tract infection",
            "Bladder cancer",
            "Urinary retention",
            "Testicular torsion",
            "Erectile dysfunction",
        ),
    ),
    Specialty(
        "plastic-surgery",
        "Plastic & Reconstructive Surgery",
        "pg_super",
        '"surgery, plastic"[MeSH Terms] OR "burns"[MeSH Terms]',
        (
            "Burns management",
            "Cleft lip and palate",
            "Flaps and grafts",
            "Hand injuries",
            "Pressure sores",
            "Keloids",
            "Facial trauma",
            "Lymphoedema",
        ),
    ),
    Specialty(
        "paediatric-surgery",
        "Paediatric Surgery",
        "pg_super",
        '"pediatrics"[MeSH Terms] AND "surgical procedures, operative"[MeSH Terms]',
        (
            "Intussusception",
            "Hypertrophic pyloric stenosis",
            "Hirschsprung disease",
            "Undescended testis",
            "Congenital diaphragmatic hernia",
            "Tracheo-oesophageal fistula",
            "Paediatric appendicitis",
            "Hypospadias",
        ),
    ),
)

BY_SLUG: dict[str, Specialty] = {s.slug: s for s in SPECIALTIES}


def get_specialty(slug: str) -> Specialty | None:
    return BY_SLUG.get(slug)
