"""Lexical retrieval — Postgres full-text search with medical synonyms.

Ranking uses ``ts_rank_cd`` (cover-density: rewards query terms appearing
close together). Medical abbreviations are expanded at query time from the
``search_synonyms`` table: a query is rewritten into OR-ed variants (the
original plus one variant per matched abbreviation), so ``afib`` also matches
"atrial fibrillation" without the user spelling it out.

``websearch_to_tsquery`` parses each variant — it never raises on odd input
and handles stop words, so the variant strings are safe to pass as parameters.

ts_rank_cd does not weigh a term by its rarity, so the passages that carry a
query's rarest term — a unique token, a rare drug name — are added after the
top hits and flagged, whatever their rank (``rare_term_passages``).
"""

from __future__ import annotations

import re
from typing import TYPE_CHECKING
from uuid import UUID

from app.repositories.base import PgConnection
from app.retrieval.types import RetrievedChunk

if TYPE_CHECKING:
    import asyncpg

TS_CONFIG = "public.clinical_english"
_MAX_VARIANTS = 6
_WORD = re.compile(r"[a-z0-9]+")
# Safety cap on raw token count before pruning (guards a pathologically long
# input); the real bounding is IDF pruning below.
_MAX_TOKENS = 40
# A lexeme matching more than this many chunks is low-information ("patients",
# "study", "among"): dropped from the OR so ts_rank_cd doesn't score a large
# fraction of the corpus. ~6.5% of the seed corpus. Tune per corpus size.
_COMMON_DF_THRESHOLD = 2000
# After pruning, keep at most this many of the *rarest* (most distinctive)
# terms — bounds worst-case ts_rank_cd work regardless of query length.
_KEEP_RAREST = 8
_MIN_KEPT_TOKENS = 2
# A query term found in at most this many passages makes them exact matches on
# something rare — a unique token, a rare drug or disease name. Ranking alone
# can bury them: ts_rank_cd has no notion of how rare a term is, so passages
# repeating the question's common words outrank the only one that carries its
# rarest. They come back flagged ``rare_term``; fusion keeps them (fusion.py)
# and the reranker places them.
RARE_TERM_PASSAGES = 10

_COLUMNS = """
            c.id            AS chunk_id,
            c.document_id   AS document_id,
            c.content       AS content,
            c.section       AS section,
            d.title         AS title,
            d.publication_date AS publication_date,
            d.evidence_grade::text AS evidence_grade,
            d.study_type::text     AS study_type,
            d.journal       AS journal,
            d.pmid          AS pmid,
            d.doi           AS doi,
            d.url           AS url,
            ts_rank_cd(c.content_tsv, q.tsq) AS rank"""


async def load_synonyms(conn: PgConnection) -> dict[str, list[str]]:
    rows = await conn.fetch("SELECT lower(term) AS term, expansion FROM public.search_synonyms")
    synonyms: dict[str, list[str]] = {}
    for row in rows:
        synonyms.setdefault(str(row["term"]), []).append(str(row["expansion"]))
    return synonyms


def build_query_variants(query: str, synonyms: dict[str, list[str]]) -> list[str]:
    """The original query plus one variant per matched abbreviation.

    Variants are generated by replacing a single matched term at a time
    (linear, not combinatorial), keeping the set small and predictable.
    """
    variants = [query.strip()]
    lowered = query.lower()
    present_tokens = set(_WORD.findall(lowered))
    for term, expansions in synonyms.items():
        # Whole-word match so "af" doesn't fire inside "affinity".
        if term in present_tokens or re.search(rf"\b{re.escape(term)}\b", lowered):
            pattern = re.compile(rf"\b{re.escape(term)}\b")
            for expansion in expansions:
                variants.append(pattern.sub(expansion, lowered))
    # De-duplicate, preserve order, cap.
    seen: set[str] = set()
    unique: list[str] = []
    for variant in variants:
        cleaned = variant.strip()
        if cleaned and cleaned not in seen:
            seen.add(cleaned)
            unique.append(cleaned)
    return unique[:_MAX_VARIANTS]


def query_tokens(query: str, synonyms: dict[str, list[str]]) -> list[str]:
    """Unique content tokens from the query and its synonym expansions.

    OR-ing these tokens (below) gives lexical *recall* — a chunk matches on any
    term and ``ts_rank_cd`` rewards chunks that match more terms, closer
    together. (AND semantics would demand every title word in one chunk, which
    never happens for a natural-language query.)
    """
    tokens: list[str] = []
    seen: set[str] = set()
    for variant in build_query_variants(query, synonyms):
        for token in _WORD.findall(variant.lower()):
            if len(token) > 1 and token not in seen:
                seen.add(token)
                tokens.append(token)
    return tokens[:_MAX_TOKENS]


async def token_frequencies(conn: PgConnection, tokens: list[str]) -> dict[str, int]:
    """Each indexed token's stemmed document frequency in ``lexeme_stats`` — 0
    when the lexeme is unknown to it (a rare drug name, a typo, anything filed
    since it was built) or it has not been built at all. Stop words, which
    are never indexed, are left out."""
    if not tokens:
        return {}
    rows = await conn.fetch(
        """
        SELECT t.token, coalesce(max(s.df), 0) AS df
        FROM unnest($1::text[]) AS t(token)
        LEFT JOIN public.lexeme_stats s
          ON s.lexeme = ANY(tsvector_to_array(to_tsvector($2::regconfig, t.token)))
        WHERE numnode(plainto_tsquery($2::regconfig, t.token)) > 0
        GROUP BY t.token
        """,
        tokens,
        TS_CONFIG,
    )
    return {str(r["token"]): int(r["df"]) for r in rows}


def prune_common_tokens(
    tokens: list[str],
    df: dict[str, int],
    *,
    threshold: int = _COMMON_DF_THRESHOLD,
    keep_rarest: int = _KEEP_RAREST,
) -> list[str]:
    """Drop low-information common terms, keep the most distinctive ones.

    Removes lexemes whose document frequency (``token_frequencies``) is above
    ``threshold`` (they match a large fraction of the corpus and blow up
    ts_rank_cd). If everything is common, keeps the rarest few so the query
    still matches something. Finally caps to the rarest ``keep_rarest``
    terms. Unknown tokens (df 0 — rare drug names, typos) are treated as
    maximally distinctive and kept. No-op until lexeme_stats is built (every
    df is 0).
    """
    kept = [t for t in tokens if df.get(t, 0) <= threshold]
    if len(kept) < _MIN_KEPT_TOKENS:
        kept = sorted(tokens, key=lambda t: df.get(t, 0))[:_MIN_KEPT_TOKENS]
    # Keep the rarest `keep_rarest`, preserving original query order among them.
    if len(kept) > keep_rarest:
        rarest = set(sorted(kept, key=lambda t: df.get(t, 0))[:keep_rarest])
        kept = [t for t in kept if t in rarest]
    return kept


def _tsquery_expression(token_count: int, first_param: int) -> str:
    """OR of per-token queries: `plainto_tsquery(cfg,$a) || ...`.

    ``plainto_tsquery`` stems each token and drops stop words to an empty
    tsquery, which is the identity for ``||`` — so no stop word can cause a
    syntax error.
    """
    parts = [f"plainto_tsquery('{TS_CONFIG}', ${first_param + i})" for i in range(token_count)]
    return " || ".join(parts)


def _hit(row: asyncpg.Record) -> RetrievedChunk:
    return RetrievedChunk(
        chunk_id=row["chunk_id"],
        document_id=row["document_id"],
        content=row["content"],
        section=row["section"],
        title=row["title"],
        publication_date=row["publication_date"],
        evidence_grade=row["evidence_grade"],
        study_type=row["study_type"],
        journal=row["journal"],
        pmid=row["pmid"],
        doi=row["doi"],
        url=row["url"],
    ).with_score("lexical", float(row["rank"]))


async def rare_term_passages(
    conn: PgConnection,
    *,
    tokens: list[str],
    terms: list[str],
    org_id: UUID | None,
    strategy: str = "structural",
    most: int = RARE_TERM_PASSAGES,
) -> list[RetrievedChunk]:
    """The passages carrying one of ``terms`` found in at most ``most`` of
    them, scored against the whole query (``tokens``) like any lexical hit,
    best first (at most ``most`` in all). Occurrences are counted live and cut
    off at ``most + 1``: lexeme_stats predates whatever was filed since it was
    built, and a term new to the corpus is exactly the one that has to count."""
    if not tokens or not terms:
        return []
    tsquery = _tsquery_expression(len(tokens), first_param=1)
    n = len(tokens) + 1
    sql = f"""
        WITH q AS (SELECT ({tsquery}) AS tsq),
        per_term AS (
            SELECT array_agg(h.id) AS ids
            FROM (
                SELECT term FROM unnest(${n}::text[]) AS term
                WHERE numnode(plainto_tsquery('{TS_CONFIG}', term)) > 0
            ) AS t
            CROSS JOIN LATERAL (
                SELECT c.id FROM public.chunks c
                WHERE c.strategy = ${n + 1}
                  AND (c.org_id IS NULL OR c.org_id = ${n + 2})
                  AND c.content_tsv @@ plainto_tsquery('{TS_CONFIG}', t.term)
                LIMIT ${n + 3}
            ) AS h
            GROUP BY t.term
        ),
        rare AS (
            SELECT DISTINCT unnest(ids) AS id FROM per_term WHERE cardinality(ids) < ${n + 3}
        )
        SELECT {_COLUMNS}
        FROM rare
        JOIN public.chunks c ON c.id = rare.id
        JOIN public.documents d ON d.id = c.document_id
        CROSS JOIN q
        ORDER BY rank DESC, c.id
        LIMIT ${n + 4}
    """
    rows = await conn.fetch(sql, *tokens, terms, strategy, org_id, most + 1, most)
    return [_hit(row) for row in rows]


async def lexical_search(
    conn: PgConnection,
    *,
    query_text: str,
    org_id: UUID | None,
    strategy: str = "structural",
    limit: int = 50,
    synonyms: dict[str, list[str]] | None = None,
    rare_terms: bool = True,
) -> list[RetrievedChunk]:
    """Top-``limit`` chunks by ts_rank_cd against the synonym-expanded query,
    then — with ``rare_terms`` — any passage carrying one of the query's rare
    terms that ranked below them (see RARE_TERM_PASSAGES). Every rare-term
    passage is flagged ``rare_term`` in its components."""
    resolved_synonyms = synonyms if synonyms is not None else await load_synonyms(conn)
    tokens = query_tokens(query_text, resolved_synonyms)
    if not tokens:
        return []
    df = await token_frequencies(conn, tokens)
    tokens = prune_common_tokens(tokens, df)
    if not tokens:
        return []

    tsquery = _tsquery_expression(len(tokens), first_param=1)
    next_param = len(tokens) + 1
    sql = f"""
        WITH q AS (SELECT ({tsquery}) AS tsq)
        SELECT {_COLUMNS}
        FROM public.chunks c
        JOIN public.documents d ON d.id = c.document_id
        CROSS JOIN q
        WHERE c.strategy = ${next_param}
          AND (c.org_id IS NULL OR c.org_id = ${next_param + 1})
          AND c.content_tsv @@ q.tsq
        ORDER BY rank DESC, c.id
        LIMIT ${next_param + 2}
    """
    rows = await conn.fetch(sql, *tokens, strategy, org_id, limit)
    hits = [_hit(row) for row in rows]
    if not rare_terms:
        return hits
    # Only a term lexeme_stats puts in few passages, or has never seen, can be
    # rare: filings since it was built only add to a count. The rest are not
    # counted again, so most queries pay nothing here.
    terms = [t for t in tokens if t in df and df[t] <= RARE_TERM_PASSAGES]
    ranked = {hit.chunk_id: hit for hit in hits}
    for passage in await rare_term_passages(
        conn, tokens=tokens, terms=terms, org_id=org_id, strategy=strategy
    ):
        hit = ranked.get(passage.chunk_id)
        if hit is None:
            hits.append(passage)
            hit = passage
        hit.components["rare_term"] = 1.0
    return hits
