"""Lexical retrieval — Postgres full-text search with medical synonyms.

Ranking uses ``ts_rank_cd`` (cover-density: rewards query terms appearing
close together). Medical abbreviations are expanded at query time from the
``search_synonyms`` table: a query is rewritten into OR-ed variants (the
original plus one variant per matched abbreviation), so ``afib`` also matches
"atrial fibrillation" without the user spelling it out.

``websearch_to_tsquery`` parses each variant — it never raises on odd input
and handles stop words, so the variant strings are safe to pass as parameters.
"""

from __future__ import annotations

import re
from uuid import UUID

from app.repositories.base import PgConnection
from app.retrieval.types import RetrievedChunk

TS_CONFIG = "public.clinical_english"
_MAX_VARIANTS = 6
_WORD = re.compile(r"[a-z0-9]+")
# Safety cap on raw token count before pruning (guards a pathologically long
# input); the real bounding is IDF pruning below.
_MAX_TOKENS = 40
# A lexeme matching more than this many chunks is low-information ("patients",
# "study", "among"): dropped from the OR so ts_rank_cd doesn't score a large
# fraction of the corpus. ~6.5% of the seed corpus. Tune per corpus size.
_COMMON_DF_THRESHOLD = 2000
# After pruning, keep at most this many of the *rarest* (most distinctive)
# terms — bounds worst-case ts_rank_cd work regardless of query length.
_KEEP_RAREST = 8
_MIN_KEPT_TOKENS = 2


async def load_synonyms(conn: PgConnection) -> dict[str, list[str]]:
    rows = await conn.fetch("SELECT lower(term) AS term, expansion FROM public.search_synonyms")
    synonyms: dict[str, list[str]] = {}
    for row in rows:
        synonyms.setdefault(str(row["term"]), []).append(str(row["expansion"]))
    return synonyms


def build_query_variants(query: str, synonyms: dict[str, list[str]]) -> list[str]:
    """The original query plus one variant per matched abbreviation.

    Variants are generated by replacing a single matched term at a time
    (linear, not combinatorial), keeping the set small and predictable.
    """
    variants = [query.strip()]
    lowered = query.lower()
    present_tokens = set(_WORD.findall(lowered))
    for term, expansions in synonyms.items():
        # Whole-word match so "af" doesn't fire inside "affinity".
        if term in present_tokens or re.search(rf"\b{re.escape(term)}\b", lowered):
            pattern = re.compile(rf"\b{re.escape(term)}\b")
            for expansion in expansions:
                variants.append(pattern.sub(expansion, lowered))
    # De-duplicate, preserve order, cap.
    seen: set[str] = set()
    unique: list[str] = []
    for variant in variants:
        cleaned = variant.strip()
        if cleaned and cleaned not in seen:
            seen.add(cleaned)
            unique.append(cleaned)
    return unique[:_MAX_VARIANTS]


def query_tokens(query: str, synonyms: dict[str, list[str]]) -> list[str]:
    """Unique content tokens from the query and its synonym expansions.

    OR-ing these tokens (below) gives lexical *recall* — a chunk matches on any
    term and ``ts_rank_cd`` rewards chunks that match more terms, closer
    together. (AND semantics would demand every title word in one chunk, which
    never happens for a natural-language query.)
    """
    tokens: list[str] = []
    seen: set[str] = set()
    for variant in build_query_variants(query, synonyms):
        for token in _WORD.findall(variant.lower()):
            if len(token) > 1 and token not in seen:
                seen.add(token)
                tokens.append(token)
    return tokens[:_MAX_TOKENS]


async def prune_common_tokens(
    conn: PgConnection,
    tokens: list[str],
    *,
    threshold: int = _COMMON_DF_THRESHOLD,
    keep_rarest: int = _KEEP_RAREST,
) -> list[str]:
    """Drop low-information common terms, keep the most distinctive ones.

    Looks up each token's stemmed document frequency in ``lexeme_stats`` and
    removes lexemes above ``threshold`` (they match a large fraction of the
    corpus and blow up ts_rank_cd). If everything is common, keeps the rarest
    few so the query still matches something. Finally caps to the rarest
    ``keep_rarest`` terms. Unknown tokens (df 0 — rare drug names, typos) are
    treated as maximally distinctive and kept. No-op until lexeme_stats is
    built (every df is 0).
    """
    if not tokens:
        return tokens
    rows = await conn.fetch(
        """
        SELECT t.token, coalesce(max(s.df), 0) AS df
        FROM unnest($1::text[]) AS t(token)
        LEFT JOIN public.lexeme_stats s
          ON s.lexeme = ANY(tsvector_to_array(to_tsvector($2::regconfig, t.token)))
        GROUP BY t.token
        """,
        tokens,
        TS_CONFIG,
    )
    df = {str(r["token"]): int(r["df"]) for r in rows}
    kept = [t for t in tokens if df.get(t, 0) <= threshold]
    if len(kept) < _MIN_KEPT_TOKENS:
        kept = sorted(tokens, key=lambda t: df.get(t, 0))[:_MIN_KEPT_TOKENS]
    # Keep the rarest `keep_rarest`, preserving original query order among them.
    if len(kept) > keep_rarest:
        rarest = set(sorted(kept, key=lambda t: df.get(t, 0))[:keep_rarest])
        kept = [t for t in kept if t in rarest]
    return kept


def _tsquery_expression(token_count: int, first_param: int) -> str:
    """OR of per-token queries: `plainto_tsquery(cfg,$a) || ...`.

    ``plainto_tsquery`` stems each token and drops stop words to an empty
    tsquery, which is the identity for ``||`` — so no stop word can cause a
    syntax error.
    """
    parts = [f"plainto_tsquery('{TS_CONFIG}', ${first_param + i})" for i in range(token_count)]
    return " || ".join(parts)


async def lexical_search(
    conn: PgConnection,
    *,
    query_text: str,
    org_id: UUID | None,
    strategy: str = "structural",
    limit: int = 50,
    synonyms: dict[str, list[str]] | None = None,
) -> list[RetrievedChunk]:
    """Top-``limit`` chunks by ts_rank_cd against the synonym-expanded query."""
    resolved_synonyms = synonyms if synonyms is not None else await load_synonyms(conn)
    tokens = query_tokens(query_text, resolved_synonyms)
    if not tokens:
        return []
    tokens = await prune_common_tokens(conn, tokens)
    if not tokens:
        return []

    tsquery = _tsquery_expression(len(tokens), first_param=1)
    next_param = len(tokens) + 1
    sql = f"""
        WITH q AS (SELECT ({tsquery}) AS tsq)
        SELECT
            c.id            AS chunk_id,
            c.document_id   AS document_id,
            c.content       AS content,
            c.section       AS section,
            d.title         AS title,
            d.publication_date AS publication_date,
            d.evidence_grade::text AS evidence_grade,
            d.study_type::text     AS study_type,
            d.journal       AS journal,
            d.pmid          AS pmid,
            d.doi           AS doi,
            d.url           AS url,
            ts_rank_cd(c.content_tsv, q.tsq) AS rank
        FROM public.chunks c
        JOIN public.documents d ON d.id = c.document_id
        CROSS JOIN q
        WHERE c.strategy = ${next_param}
          AND (c.org_id IS NULL OR c.org_id = ${next_param + 1})
          AND c.content_tsv @@ q.tsq
        ORDER BY rank DESC, c.id
        LIMIT ${next_param + 2}
    """
    rows = await conn.fetch(sql, *tokens, strategy, org_id, limit)
    return [
        RetrievedChunk(
            chunk_id=row["chunk_id"],
            document_id=row["document_id"],
            content=row["content"],
            section=row["section"],
            title=row["title"],
            publication_date=row["publication_date"],
            evidence_grade=row["evidence_grade"],
            study_type=row["study_type"],
            journal=row["journal"],
            pmid=row["pmid"],
            doi=row["doi"],
            url=row["url"],
        ).with_score("lexical", float(row["rank"]))
        for row in rows
    ]
